// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmNMQoasmkCdnXyVU-xn0cBVBraApWKc',
    appId: '1:1091569061800:web:5b5409786358e2e38d979d',
    messagingSenderId: '1091569061800',
    projectId: 'fierbacelogin',
    authDomain: 'fierbacelogin.firebaseapp.com',
    storageBucket: 'fierbacelogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF2M5wHZOXHOdcs6DmmN2H-oroJL4Ye2g',
    appId: '1:1091569061800:android:6160849489d1dbc18d979d',
    messagingSenderId: '1091569061800',
    projectId: 'fierbacelogin',
    storageBucket: 'fierbacelogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_irrgvyKhb-8gcT7nrqVkgDjOfy0kRy8',
    appId: '1:1091569061800:ios:ed957bf696c0f7c38d979d',
    messagingSenderId: '1091569061800',
    projectId: 'fierbacelogin',
    storageBucket: 'fierbacelogin.appspot.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_irrgvyKhb-8gcT7nrqVkgDjOfy0kRy8',
    appId: '1:1091569061800:ios:ed957bf696c0f7c38d979d',
    messagingSenderId: '1091569061800',
    projectId: 'fierbacelogin',
    storageBucket: 'fierbacelogin.appspot.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTmNMQoasmkCdnXyVU-xn0cBVBraApWKc',
    appId: '1:1091569061800:web:40a2a1e4f6ee3fae8d979d',
    messagingSenderId: '1091569061800',
    projectId: 'fierbacelogin',
    authDomain: 'fierbacelogin.firebaseapp.com',
    storageBucket: 'fierbacelogin.appspot.com',
  );
}
